### ISSUE TITLE
Problem connecting the SQS [question]

### ISSUE THREAD

**Issue by green-coder** [open-company/open-company-auth#81]
Hi,

I am trying to run `open-company-auth`, but I am running into a problem while connecting the SQS queues:

![image](https://user-images.githubusercontent.com/598193/56679865-9c32ac80-66f8-11e9-9626-917d9e2a2e44.png)

Do you have an idea of what the problem could be?

**Comment by bago2k4** [comment]
@green-coder in order to start auth service you need a few SQS configured on your account. Unfortunately you can't use our queues with your credentials.
But from the screenshot it looks like you are missing the region env var. try this before you start the auth service:
```
export AWS_REGION='us-east-1'
```
if it works you can add it to your `.profile`

**Comment by belucid** [comment]
Also let us know if that fixes it so we can update the README to be more comprehensive. Thanks @green-coder

**Comment by green-coder** [comment]
It worked, but after I specified `export AWS_REGION='us-east-1'` the program was ignoring the credentials defined in `project.clj` and was expecting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to be defined in the same manner as well.
